(function(global){
 'use strict';
 /** @typedef {import('../../shared/contracts/index.js').SourceDraft} SourceDraft */
 /** @typedef {import('../../shared/contracts/index.js').RenderPlan} RenderPlan */
 /** @typedef {import('../../shared/contracts/index.js').TargetSnapshot} TargetSnapshot */
 var hosts={}, capabilities={}, originalState=global.RAChangeState;
 function clone(x){return JSON.parse(JSON.stringify(x))}
 function equal(a,b){return originalState.equal(a&&a.comparison||a,b&&b.comparison||b)}
 function appFor(kind){
  var method={et:'EtApplication',wpp:'WppApplication',wps:'WpsApplication'}[kind],candidates=[];
  try{if(global.wps&&method&&global.wps[method])candidates.push(global.wps[method]())}catch(e){}
  try{if(global.Application)candidates.push(typeof global.Application==='function'?global.Application():global.Application)}catch(e){}
  try{if(global.wps&&global.wps.Application)candidates.push(typeof global.wps.Application==='function'?global.wps.Application():global.wps.Application)}catch(e){}
  return candidates.find(function(a){try{return a&&!!a[{et:'ActiveWorkbook',wpp:'ActivePresentation',wps:'ActiveDocument'}[kind]]}catch(e){return false}})||null;
 }
 function metadata(doc,kind){var key=String(doc.FullName||'');if(!doc.Path&&!/[\\/]/.test(key))throw new Error('请先保存当前文件，再加入项目');return {key:key,name:String(doc.Name||key),kind:kind,capabilities:Object.keys(capabilities).filter(function(id){return capabilities[id].host===kind})}}
 function registerHost(h){if(!h.id||hosts[h.id])throw new Error('宿主标识无效或重复');['app','document'].forEach(function(k){if(typeof h[k]!=='function')throw new Error('宿主缺少 '+k)});hosts[h.id]=h}
 function registerCapability(c){if(!c.id||capabilities[c.id]||!hosts[c.host])throw new Error('能力标识无效或宿主未注册');['selection','read','locate','snapshot','preflight','apply','restore'].forEach(function(k){if(typeof c[k]!=='function')throw new Error('能力缺少 '+k)});capabilities[c.id]=c}
 function capability(id){if(!capabilities[id])throw new Error('当前安装不包含能力：'+id);return capabilities[id]}
 function wrap(target){var id=target.capabilityId||'wpp.object',c=capability(id);return {capability:c,target:target,object:c.locate(target.locator||target)}}
 function snapshot(w){w.object=w.capability.locate(w.target.locator||w.target);return w.capability.snapshot(w.object,w.target.locator||w.target)}
 function restore(w,s){w.capability.restore(w.object,s,w.target.locator||w.target);if(!equal(snapshot(w),s))throw new Error('恢复结果与历史记录不一致，请检查原文件')}
 function tableRows(t,writer){var rows=[];for(var r=1;r<=t.Rows.Count;r++){var row=[];for(var c=1;c<=t.Columns.Count;c++){var cell=t.Cell(r,c);row.push(writer?String(cell.Range.Text||'').replace(/[\r\x07]+$/,''):String(cell.Shape.TextFrame.TextRange.Text||''))}rows.push(row)}return rows}
 function values(v){return Array.isArray(v)?(Array.isArray(v[0])?v:v.map(function(x){return[x]})):[[v]]}
 function addr(r){return String(typeof r.Address==='function'?r.Address():r.Address)}
 function resolveSelection(sheet,requested){
  var raw=String(requested).replace(/\$/g,''),r=sheet.Range(requested),mode='range';
  var wholeColumns=/^[A-Za-z]+:[A-Za-z]+$/.test(raw)||Number(r.Rows.Count)>=Number(sheet.Rows&&sheet.Rows.Count||1048576);
  var wholeRows=/^\d+:\d+$/.test(raw)||Number(r.Columns.Count)>=Number(sheet.Columns&&sheet.Columns.Count||16384);
  if(wholeColumns&&wholeRows)mode='whole-sheet';else if(wholeColumns)mode='whole-columns';else if(wholeRows)mode='whole-rows';
  if(mode!=='range'){
   var used=sheet.UsedRange;if(!used)throw new Error('无法读取工作表已用区域');
   var top=Math.max(Number(r.Row||1),Number(used.Row||1)),left=Math.max(Number(r.Column||1),Number(used.Column||1));
   var bottom=Math.min(Number(r.Row||1)+Number(r.Rows.Count)-1,Number(used.Row||1)+Number(used.Rows.Count)-1),right=Math.min(Number(r.Column||1)+Number(r.Columns.Count)-1,Number(used.Column||1)+Number(used.Columns.Count)-1);
   if(bottom<top||right<left)throw new Error('选区与已用区域没有交集');
   function col(n){var out='';while(n){n--;out=String.fromCharCode(65+n%26)+out;n=Math.floor(n/26)}return out}
   r=sheet.Range('$'+col(left)+'$'+top+':$'+col(right)+'$'+bottom);
  }
  if(Number(r.Rows.Count)>5001||Number(r.Columns.Count)>200)throw new Error('单次读取最多 5000 行数据（另加表头）、200 列');
  return {range:r,requestedAddress:requested,effectiveAddress:addr(r),selectionMode:mode};
 }
 function cells(r,fn){var rows=[];for(var y=1;y<=Number(r.Rows.Count);y++){var row=[];for(var x=1;x<=Number(r.Columns.Count);x++)row.push(fn(r.Cells.Item(y,x),y,x));rows.push(row)}return rows}
 function properties(obj,keys){var out={};keys.forEach(function(k){var v=obj[k];if(v!==undefined&&v!==null&&(typeof v==='string'||typeof v==='number'||typeof v==='boolean'))out[k]=v});return out}
 function inspectHost(kind){
  var app=hosts[kind].app(),doc=app[{et:'ActiveWorkbook',wpp:'ActivePresentation',wps:'ActiveDocument'}[kind]],targets=[];
  if(kind==='et'){
   var sheets=doc.Worksheets||doc.Sheets,result=[];for(var i=1;i<=Number(sheets.Count);i++){var sheet=sheets.Item(i),used=sheet.UsedRange,rows=Number(used&&used.Rows.Count||0),cols=Number(used&&used.Columns.Count||0),address=used?addr(used):'';var headers=[];if(used&&rows&&cols)for(var c=1;c<=Math.min(cols,40);c++)headers.push(String(used.Cells.Item(1,c).Value2||''));result.push({name:String(sheet.Name),usedRange:address,rowCount:rows,columnCount:cols,headers:headers});if(used&&rows*cols<=2000)targets.push({capabilityId:'et.range',kind:'table',label:String(sheet.Name)+'!'+address,locator:{sheetName:String(sheet.Name),address:address}})}return {kind:'spreadsheet',sheets:result,targets:targets};
  }
  if(kind==='wpp'){
   var slides=doc.Slides,result=[];for(var si=1;si<=Number(slides.Count);si++){var slide=slides.Item(si),objects=[];for(var oi=1;oi<=Number(slide.Shapes.Count);oi++){var shape=slide.Shapes.Item(oi),table=shape.HasTable===-1||shape.HasTable===true,text='';try{text=String(shape.TextFrame.TextRange.Text||'').slice(0,300)}catch(e){}var objectKind=table?'table':text?'text':'shape',locator={slideId:Number(slide.SlideID),shapeId:Number(shape.Id)},target={capabilityId:'wpp.object',kind:table?'table':'text',label:'第 '+si+' 页 · '+String(shape.Name),locator:locator};objects.push({objectId:Number(shape.Id),kind:objectKind,summary:text||String(shape.Name),bbox:{x:Number(shape.Left||0),y:Number(shape.Top||0),width:Number(shape.Width||0),height:Number(shape.Height||0)}});if(table||text)targets.push(target)}result.push({slideId:Number(slide.SlideID),index:si,title:objects.length?objects[0].summary:'',objects:objects})}return {kind:'presentation',slides:result,targets:targets};
  }
  var paragraphs=[],count=Number(doc.Paragraphs&&doc.Paragraphs.Count||0);for(var pi=1;pi<=Math.min(count,200);pi++){var para=doc.Paragraphs.Item(pi),range=para.Range,text=String(range.Text||'').replace(/[\r\x07]+$/,'');if(!text.trim())continue;var locator={start:Number(range.Start),end:Number(range.End),originalText:String(range.Text||''),bookmark:'RA_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)};paragraphs.push({index:pi,text:text.slice(0,300)});targets.push({capabilityId:'wps.range',kind:'text',label:'段落 '+pi,locator:locator})}
  var tables=[];for(var ti=1;ti<=Number(doc.Tables&&doc.Tables.Count||0);ti++){var table=doc.Tables.Item(ti),tr=table.Range;tables.push({index:ti,rows:Number(table.Rows.Count),columns:Number(table.Columns.Count)});targets.push({capabilityId:'wps.range',kind:'table',label:'表格 '+ti,locator:{start:Number(tr.Start),end:Number(tr.End),originalText:String(tr.Text||''),bookmark:'RA_T_'+Date.now().toString(36)+'_'+ti}})}
  return {kind:'writer',paragraphs:paragraphs,tables:tables,targets:targets};
 }
 function set(obj,p){Object.keys(p).forEach(function(k){obj[k]=p[k]})}
 function mergeSpecs(p){var raw=p&&p.mergeCells;if(raw===undefined||raw===null)return[];if(!Array.isArray(raw))throw new Error('mergeCells 必须是数组');return raw.map(function(x,i){x=x||{};var m={row:Number(x.row),column:Number(x.column),rowSpan:Number(x.rowSpan),colSpan:Number(x.colSpan)};if(!isFinite(m.row)||!isFinite(m.column)||!isFinite(m.rowSpan)||!isFinite(m.colSpan)||m.row<1||m.column<1||m.rowSpan<2||m.colSpan<1||Math.floor(m.row)!==m.row||Math.floor(m.column)!==m.column||Math.floor(m.rowSpan)!==m.rowSpan||Math.floor(m.colSpan)!==m.colSpan)throw new Error('mergeCells['+i+'] 范围无效');return m})}
 function mergeRange(r,m){var start=r.Cells.Item(m.row,m.column),end=r.Cells.Item(m.row+m.rowSpan-1,m.column+m.colSpan-1);if(start&&typeof start.Resize==='function')return start.Resize(m.rowSpan,m.colSpan);if(r&&typeof r.Range==='function')return r.Range(start,end);if(r&&r.Parent&&typeof r.Parent.Range==='function')return r.Parent.Range(start,end);throw new Error('当前 WPS 版本缺少单元格合并范围接口')}
 function areaOf(cell){var area;try{area=cell.MergeArea}catch(e){area=null}if(typeof area==='function'){try{area=area()}catch(e){area=null}}return area}
 function captureMerges(r){var out=[],seen={};for(var y=1;y<=Number(r.Rows.Count);y++)for(var x=1;x<=Number(r.Columns.Count);x++){var cell=r.Cells.Item(y,x);if(!cell.MergeCells)continue;var area=areaOf(cell);if(!area||!area.Rows||!area.Columns)throw new Error('无法读取现有合并区域');var h=Number(area.Rows.Count),w=Number(area.Columns.Count),top=y,left=x,baseRow=Number(r.Row),baseCol=Number(r.Column),areaRow=Number(area.Row),areaCol=Number(area.Column);if(isFinite(baseRow)&&isFinite(baseCol)&&isFinite(areaRow)&&isFinite(areaCol)){top=areaRow-baseRow+1;left=areaCol-baseCol+1}if(!isFinite(h)||!isFinite(w)||h<1||w<1||top<1||left<1||top+h-1>Number(r.Rows.Count)||left+w-1>Number(r.Columns.Count))throw new Error('合并区域超出当前选区');var key=top+':'+left+':'+h+':'+w;if(!seen[key]){seen[key]=true;out.push({row:top,column:left,rowSpan:h,colSpan:w})}}return out}
 function unmerge(r){if(!r.MergeCells)return;if(typeof r.UnMerge!=='function')throw new Error('当前 WPS 版本缺少取消合并接口');r.UnMerge()}
 ['et','wps','wpp'].forEach(function(id){registerHost({id:id,label:{et:'WPS 表格',wps:'WPS 文字',wpp:'WPS 演示'}[id],app:function(){var a=appFor(id);if(!a)throw new Error('没有连接到 '+hosts[id].label);return a},document:function(){var a=this.app();return metadata(a[{et:'ActiveWorkbook',wps:'ActiveDocument',wpp:'ActivePresentation'}[id]],id)},inspect:function(){return inspectHost(id)}})});
 registerCapability({id:'et.range',host:'et',label:'单元格区域',inputTypes:['table'],outputTypes:['text','table'],
  selection:function(kind){var a=hosts.et.app(),r=a.Selection;return {capabilityId:this.id,kind:kind||'table',locator:{sheetName:String(a.ActiveSheet.Name),address:addr(r)},label:String(a.ActiveSheet.Name)+'!'+addr(r)}},
  locate:function(l){return hosts.et.app().ActiveWorkbook.Worksheets.Item(l.sheetName).Range(l.address)},
  read:function(l){var sheet=hosts.et.app().ActiveWorkbook.Worksheets.Item(l.sheetName),resolved=resolveSelection(sheet,l.requestedAddress||l.address),r=resolved.range;var captured=Number(r.Rows.Count)===1&&Number(r.Columns.Count)===1?[['值'],[r.Value2]]:values(r.Value2);return {values:captured,headersMode:'first-row',capabilityId:this.id,locator:Object.assign({},l,{requestedAddress:resolved.requestedAddress,address:resolved.requestedAddress}),sheetName:l.sheetName,address:resolved.requestedAddress,requestedAddress:resolved.requestedAddress,effectiveAddress:resolved.effectiveAddress,selectionMode:resolved.selectionMode}},
  snapshot:function(r){if(r.Rows.Count*r.Columns.Count>2000)throw new Error('单次修改最多 2000 个单元格');return {version:1,kind:'table',adapterId:this.id,cells:cells(r,function(c){if(c.NumberFormat==null||!c.Font)throw new Error('此 WPS 版本缺少单元格格式快照能力');return {text:String(c.Value2==null?'':c.Value2),value:c.Value2==null?null:c.Value2,formula:c.HasFormula?String(c.Formula):null,format:String(c.NumberFormat),font:properties(c.Font,['Name','Size','Bold','Italic','Underline','Color']),alignment:properties(c,['HorizontalAlignment','VerticalAlignment','WrapText'])}}),merges:captureMerges(r)}},
  preflight:function(r,p){var matrix=p.kind==='text'?[[p.text]]:(p.header?[p.header]:[]).concat(p.rows||[]);if(p.kind!=='text'&&p.kind!=='table')throw new Error('单元格能力不支持此输出类型');if(matrix.length>r.Rows.Count||matrix.some(function(x){return x.length>r.Columns.Count}))throw new Error('输出需要 '+matrix.length+' 行，请选中足够大的目标区域');if(r.MergeCells)throw new Error('暂不支持在已有合并区域中写入');mergeSpecs(p).forEach(function(m){if(m.row+m.rowSpan-1>r.Rows.Count||m.column+m.colSpan-1>r.Columns.Count)throw new Error('合并区域超出目标选区');mergeRange(r,m)})},
  apply:function(r,p){this.preflight(r,p);var matrix=p.kind==='text'?[[p.text]]:(p.header?[p.header]:[]).concat(p.rows||[]);matrix.forEach(function(row,y){row.forEach(function(v,x){var c=r.Cells.Item(y+1,x+1),fmt=c.NumberFormat;c.NumberFormat='@';c.Value2=String(v==null?'':v);c.NumberFormat=fmt})});mergeSpecs(p).forEach(function(m){mergeRange(r,m).Merge()})},
  restore:function(r,s){if(r.Rows.Count!==s.cells.length||r.Columns.Count!==s.cells[0].length)throw new Error('目标区域结构已改变');unmerge(r);s.cells.forEach(function(row,y){row.forEach(function(old,x){var c=r.Cells.Item(y+1,x+1);if(old.formula!==null){c.Formula=old.formula}else{c.NumberFormat='@';c.Value2=old.value}c.NumberFormat=old.format;set(c.Font,old.font);set(c,old.alignment)})});(s.merges||[]).forEach(function(m){mergeRange(r,m).Merge()})}
 });
 registerCapability({id:'wpp.object',host:'wpp',label:'幻灯片对象',inputTypes:['text','table'],outputTypes:['text','table'],
  selection:function(){var a=hosts.wpp.app(),slide=a.ActiveWindow.View.Slide,shape=a.ActiveWindow.Selection.ShapeRange.Item(1),kind=shape.HasTable===-1||shape.HasTable===true?'table':'text';return {capabilityId:this.id,kind:kind,locator:{slideId:Number(slide.SlideID),shapeId:Number(shape.Id)},label:'第 '+slide.SlideIndex+' 页 · '+shape.Name,slideIndex:Number(slide.SlideIndex),shapeName:String(shape.Name)}},
  locate:function(l){var slides=hosts.wpp.app().ActivePresentation.Slides;for(var i=1;i<=slides.Count;i++){var slide=slides.Item(i);if(Number(slide.SlideID)===Number(l.slideId))for(var j=1;j<=slide.Shapes.Count;j++){var shape=slide.Shapes.Item(j);if(Number(shape.Id)===Number(l.shapeId))return shape}}throw new Error('找不到原幻灯片对象')},
  read:function(l){var s=this.locate(l),v=(s.HasTable===-1||s.HasTable===true)?tableRows(s.Table,false):[['内容'],[String(s.TextFrame.TextRange.Text||'')]];return {values:v,headersMode:'first-row',capabilityId:this.id,locator:clone(l)}},
  snapshot:function(s){return originalState.capture(s)},preflight:function(s,p){originalState.preflight(s,p)},apply:function(s,p){originalState.apply(s,p)},restore:function(s,before){originalState.restore(s,before)}
 });
 function writerRange(l){var doc=hosts.wps.app().ActiveDocument;if(l.bookmark&&doc.Bookmarks.Exists(l.bookmark))return doc.Bookmarks.Item(l.bookmark).Range;var r=doc.Range(l.start,l.end);if(l.originalText!==undefined&&String(r.Text||'')!==l.originalText)throw new Error('原文字选区已变化或定位书签已删除，请重新选择目标');return r}
 function cleanXML(xml){if(!global.DOMParser)return xml;var doc=new DOMParser().parseFromString(xml,'application/xml');Array.prototype.slice.call(doc.getElementsByTagName('*')).forEach(function(node){if(node.localName==='part'&&/\/docProps\//.test(node.getAttribute('pkg:name')||'')){node.parentNode.removeChild(node);return}Array.prototype.slice.call(node.attributes||[]).forEach(function(a){if(/^rsid/.test(a.localName))node.removeAttributeNode(a)})});return new XMLSerializer().serializeToString(doc)}
 registerCapability({id:'wps.range',host:'wps',label:'文字或表格选区',inputTypes:['text','table'],outputTypes:['text','table'],
  selection:function(){var a=hosts.wps.app(),r=a.Selection.Range;if(r.Start===r.End)throw new Error('请先选中要读取或替换的文字/表格');return {capabilityId:this.id,kind:r.Tables.Count?'table':'text',locator:{start:Number(r.Start),end:Number(r.End),originalText:String(r.Text||''),bookmark:'RA_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)},label:'文字选区 '+r.Start+'–'+r.End}},
  locate:writerRange,
  read:function(l){var r=this.locate(l),v=r.Tables.Count?tableRows(r.Tables.Item(1),true):[['内容'],[String(r.Text||'')]];return {values:v,headersMode:'first-row',capabilityId:this.id,locator:clone(l)}},
  snapshot:function(r,l){var doc=hosts.wps.app().ActiveDocument;if(doc.TrackRevisions)throw new Error('请先关闭此文稿的修订记录，再使用插件修改');var xml=r.WordOpenXML;if(typeof xml!=='string'||!xml||!r.InsertXML)throw new Error('此 WPS 版本缺少文字格式快照/恢复能力');var present=!!doc.Bookmarks.Exists(l.bookmark),text=String(r.Text||''),tableValues=r.Tables.Count?tableRows(r.Tables.Item(1),true):undefined;return {version:1,kind:'text',adapterId:this.id,text:{text:text},cells:tableValues,xml:xml,comparison:{adapterId:this.id,text:text,xml:cleanXML(xml),bookmark:present},bookmarkPresent:present,start:Number(r.Start),end:Number(r.End)}},
  preflight:function(r,p){if(hosts.wps.app().ActiveDocument.ReadOnly)throw new Error('文稿为只读');if(p.kind==='table'){if(!r.Tables.Count)throw new Error('请选中一个文字表格作为输出目标');var t=r.Tables.Item(1),rows=(p.header?[p.header]:[]).concat(p.rows||[]);if(rows.length>t.Rows.Count||rows.some(function(row){return row.length>t.Columns.Count}))throw new Error('目标表格空间不足，请扩大选区')}else if(p.kind!=='text')throw new Error('文字能力不支持此输出类型')},
  apply:function(r,p,l){this.preflight(r,p);var start=Number(r.Start),doc=hosts.wps.app().ActiveDocument;if(p.kind==='text'){r.Text=String(p.text||'');r=doc.Range(start,start+String(p.text||'').length)}else{var t=r.Tables.Item(1);(p.header?[p.header]:[]).concat(p.rows||[]).forEach(function(row,y){row.forEach(function(v,x){var cell=t.Cell(y+1,x+1).Range;cell.End=cell.End-1;cell.Text=String(v==null?'':v)})});r=t.Range}doc.Bookmarks.Add(l.bookmark,r)},
  restore:function(r,s,l){var doc=hosts.wps.app().ActiveDocument;r.InsertXML(s.xml);var restored=doc.Range(s.start,s.end);if(s.bookmarkPresent)doc.Bookmarks.Add(l.bookmark,restored);else if(doc.Bookmarks.Exists(l.bookmark))doc.Bookmarks.Item(l.bookmark).Delete()}
 });
 global.RAHosts={resolveSelection:resolveSelection,registerHost:registerHost,registerCapability:registerCapability,hosts:hosts,capabilities:capabilities,capability:capability,resolve:wrap,forHost:function(id){return Object.keys(capabilities).map(function(k){return capabilities[k]}).filter(function(c){return c.host===id})}};
 global.RAChangeState={capture:snapshot,restore:restore,equal:equal,clone:clone,preflight:function(w,p){w.capability.preflight(w.object,p,w.target.locator||w.target)},apply:function(w,p){w.capability.apply(w.object,p,w.target.locator||w.target)},content:function(s){if(s&&s.kind!=="text"&&s.kind!=="table")return String(s.summary||"对象内容与格式快照");return originalState.content(s)}};
})(typeof window!=='undefined'?window:globalThis);
